### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-merge-rs#9]
i.e. to replicate [ocdskit compile](https://ocdskit.readthedocs.io/en/latest/cli/ocds.html#compile)

Needed for https://github.com/open-contracting/deploy/issues/437

To start, can accept release packages only, then also record packages (like from Kingfisher Collect).

For JSON streams: https://docs.rs/serde_json/latest/serde_json/struct.StreamDeserializer.html

## Alternatives to using sqlite like in OCDS Kit

SQL-like

* https://github.com/rusqlite/rusqlite best choice if SQLite is enough
* https://lib.rs/crates/duckdb [reported](https://github.com/jqnatividad/qsv/pull/800) to cause slow compilation (>1 hour?)

Key-value

* LMDB crates, probably https://github.com/meilisearch/heed/releases
  * key = ocid, value = list of releases
  * Need to learn how heed serializes/deserializes
  * Has no functions for updating existing values, would need to do a get/set
* https://lib.rs/crates/sled in "beta" for many years, memory overconsumption issues
  * Has some [functions](https://docs.rs/sled/latest/sled/struct.Db.html) for updating existing values, though it looks like they do a get/set
* https://lib.rs/crates/rocksdb [reported](https://github.com/romanz/electrs/issues/201) to cause slow compilation (hours), otherwise probably faster than sled

**Comment by jpmckinney** [comment]
Other old notes from 2023 (with small updates):

- Check edge cases in record_compiler.py and release_compiler.py
- To use ProfileBuilder, either need to write part of the CLI in Python, or need to call Python from Rust https://pyo3.rs/v0.26.0/python-from-rust.html
- ChatGPT session about LMDBs, unlikely to still be relevant: https://chatgpt.com/c/d511bf14-11ac-4146-8d21-b5aade5cc410

Miscellaneous optimization ideas:

- Store intermediate data as MessagePack using [rmp](https://docs.rs/rmp/latest/rmp/)? e.g. using [rmp-serde](https://docs.rs/rmp-serde/latest/rmp_serde/) to serialize from the original JSON, and [rmpv](https://docs.rs/rmpv/latest/rmpv/) to deserialize when appending to lists of releases ([like here](https://github.com/iliakonnov/lmtreedb/blob/415e47b968eed9ac3e3fc250251ba651d4e0df70/src/lib.rs#L90-L96)). Note that rpm does lazy deserialization.

**Comment by jpmckinney** [comment]
Until we add a CLI, there isn't much reason to release the Rust version. Moving the `release.yml` workflow here for now.

<details>

```yml
name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (like 0.0.1)'
        required: true
        type: string
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ inputs.tag || github.ref_name }}
  assets:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Aim for one option per major OS per 64-bit architecture, taking from "Tier 1 with Host Tools" targets and,
        # if needed, "Tier 2 with Host Tools" targets.
        # https://doc.rust-lang.org/rustc/platform-support.html
        # https://github.com/cross-rs/cross#supported-targets
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        include:
          # 64-bit (x86)
          - build: linux-64-bit
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          - build: macos-64-bit
            os: macos-latest
            target: x86_64-apple-darwin
            command: cargo
          - build: windows-64-bit
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: cross
          # 64-bit (ARM)
          # aarch64-pc-windows requires https://github.com/cross-rs/cross-toolchains#targets
          # "`cross` does not provide a Docker image for target aarch64-pc-windows-gnullvm"
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
            command: cargo
          - build: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: ${{ matrix.command }} build --release --target ${{ matrix.target }} --bin ocdsmerge --no-default-features
      # 7z is available on all runners.
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      - name: Create archive
        id: archive
        shell: bash
        run: |
          DIRECTORY="ocdsmerge-${{ inputs.tag || github.ref_name }}-${{ matrix.build }}"
          if [[ "${{ matrix.target }}" =~ "-pc-windows-" ]]; then
            SUFFIX=".exe"
          else
            SUFFIX=""
          fi
          mkdir "$DIRECTORY"
          cp docs/changelog.md LICENSE README.md "target/${{ matrix.target }}/release/ocdsmerge$SUFFIX" "$DIRECTORY"
          7z a "$DIRECTORY.zip" "$DIRECTORY"
          echo "path=$DIRECTORY.zip" >> $GITHUB_OUTPUT
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ inputs.tag || github.ref_name }} ${{ steps.archive.outputs.path }} ${{ inputs.tag && '--clobber' || '' }}
```

</details>
